### ISSUE TITLE
Some systems failed to build for Quicklisp dist

### ISSUE THREAD

**Issue by quicklisp** [melusina-org/cl-atelier#1]
Building with SBCL 2.2.4 / ASDF 3.3.5 for quicklisp dist creation.

Trying to build commit id ad659c165d38bcc972635fbe10bd5ed4e1d40b03

*org.melusina.atelier* fails to build with the following error:

```
; caught WARNING:
;   Duplicate definition for FIND-TEMPLATE found in one file.
;   See also:
;     The ANSI Standard, Section 3.2.2.3
...
Unhandled UIOP/LISP-BUILD:COMPILE-FILE-ERROR in thread #<SB-THREAD:THREAD "main thread" RUNNING {1001C58003}>: COMPILE-FILE-ERROR while compiling #<CL-SOURCE-FILE "org.melusina.atelier" "src" "template">

```

*org.melusina.atelier/testsuite* fails to build because of a failure in  _org.melusina.atelier_.

[Full log here](http://report.quicklisp.org/2022-06-21/failure-report/cl-atelier.html)

**Comment by foretspaisibles** [comment]
This is fixed in 918ee0356779cac3c019dd7694f3f27df14bf910, thanks!
